### ISSUE TITLE
Bug - typo

### ISSUE THREAD

**Issue by jesuscontrerasocana** [klaus-rheinberger/AggrFlex_Supplement#1]
Typo in lines 183 and 185 of algo_Union_Homothets_Stage_0.py. 

should be:

    constraints  = []
    for i in range(len(r_list)):
        constraints = constraints + [xp[0]-xm[0] == r_list[i]*(xp[i+1]-xm[i+1])]

**Comment by klaus-rheinberger** [comment]
Thank you for reporting the typo! We have corrected the typos in the algorithms algo_Union_Homothets_Stage_0.py and algo_Union_Homothets_Stage_1.py.
